### ISSUE TITLE
Error on attempt to uninstall the windows shipper service

### ISSUE THREAD

**Issue by fandrei** [cityindex-attic/logsearch#187]
I'm getting this error message when trying to reinstall a windows shipper service:

```
Uninstalling existing windows-shipper-service.exe service
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServiceProxy.StopService()
   at winsw.WrapperService.Run(String[] _args)
   at winsw.WrapperService.Main(String[] args)
```

**Comment by mwolff-unl** [comment]
In my case it stays open indefinitely.
